# Generated by Django 4.2 on 2023-12-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeModel',
            fields=[
                ('pc_id', models.AutoField(primary_key=True, serialize=False)),
                ('balance', models.BigIntegerField()),
                ('binary_field', models.BinaryField()),
                ('active', models.BooleanField()),
                ('name', models.CharField(max_length=50)),
                ('birth_day', models.DateField()),
                ('appointment', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration', models.DurationField()),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('slug', models.SlugField()),
                ('comment', models.TextField()),
                ('today', models.TimeField()),
                ('img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
